print("Good Morning India!")
print("Hi")
print("This is from demo branch")
print("This is from demo branch to merge in main branch")
print("This is from demo1 branch who wants to get merge in main branch")
print("This is updated demo1 branch and now going to merge this demo1 branch to main branch without conflicts")